name: flutter_note
description: A Flutter Project of compilation of everything I learn about flutter.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.3
  dio: ^5.0.3
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  fluro: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  infinite_listview: ^1.1.0
  intl: ^0.18.0
  intl_utils: ^2.8.2
  json_annotation: ^4.8.0
  logger: ^1.3.0
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true
